name: Cleanup deployed storybook
on:
  pull_request:
    types: [closed]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  storybook-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "::set-env name=BRANCH_NAME::${GITHUB_HEAD_REF}"

      - name: remove directory in gh pages
        run: |
          echo "Removing GH pages directory: ${{env.BRANCH_NAME}}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          touch .empty
          npx gh-pages --dist . --src .empty --remove "${{env.BRANCH_NAME}}" --no-history --repo "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
